#!/bin/sh

# Zsh initial
if [ ! -d Github ]; then
    mkdir -v Github
fi

if [ ! -d Github/oh-my-zsh ]; then
    git clone https://github.com/robbyrussell/oh-my-zsh.git Github/oh-my-zsh
fi

if [ ! -d Github/Powerline-Menlo ]; then
    git clone https://github.com/abertsch/Menlo-for-Powerline.git Github/Powerline-Menlo
fi

if [ -L ~/.zshrc ]; then
    /bin/rm ~/.zshrc
fi
ln -sv `pwd`/zshrc ~/.zshrc

if [ -L ~/.oh-my-zsh ]; then
    /bin/rm ~/.oh-my-zsh
fi
ln -sv `pwd`/Github/oh-my-zsh ~/.oh-my-zsh

if [ -L ~/.zsh_customization ]; then
    /bin/rm ~/.zsh_customization
fi
ln -sv `pwd`/zsh_customization ~/.zsh_customization

# Vim initial

if [ ! -d Vimdir/bundle ]; then
    mkdir -v Vimdir/bundle
fi

if [ ! -d Vimdir/bundle/Vundle.vim/ ]; then
    git clone https://github.com/gmarik/vundle.git Vimdir/bundle/Vundle.vim
fi

if [ -L ~/.vim ]; then
    /bin/rm ~/.vim
fi
ln -sv `pwd`/Vimdir ~/.vim

if [ -L ~/.vimrc ]; then
    /bin/rm ~/.vimrc
fi
ln -sv `pwd`/vimrc ~/.vimrc

if [ -L ~/.ycm_extra_conf.py ]; then
    /bin/rm ~/.ycm_extra_conf.py
fi
ln -sv `pwd`/ycm_extra_conf.py ~/.ycm_extra_conf.py

# Tmux initial

if [ ! -d tmuxdir ]; then
    mkdir -v tmuxdir
fi

if [ ! -d tmuxdir/plugins ]; then
    mkdir -v tmuxdir/plugins
fi

if [ ! -d tmuxdir/plugins/tpm ]; then
    git clone https://github.com/tmux-plugins/tpm tmuxdir/plugins/tpm
fi

if [ -L ~/.tmux ]; then
    /bin/rm ~/.tmux
fi
ln -sv `pwd`/tmuxdir ~/.tmux

if [ -L ~/.tmux.conf ]; then
    /bin/rm ~/.tmux.conf
fi
ln -sv `pwd`/tmux.conf ~/.tmux.conf

